-- Nexus database schema for Supabase (free tier — plenty for 10–15 staff).
-- Run in: Supabase Dashboard → SQL Editor → New query → paste → Run.

-- Profiles mirror signed-in users (Supabase Auth email as identity).
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  display_name text,
  created_at timestamptz not null default now()
);

-- Chat threads per user. Id is the client-generated slug from useConversations'
-- uid() helper (e.g. "c-abc123-de45"), not a uuid — the browser is the source
-- of an id for a conversation the moment it's created, so the row must accept
-- that id directly rather than generating its own on insert.
create table if not exists public.conversations (
  id text primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists conversations_user_updated_idx
  on public.conversations (user_id, updated_at desc);

-- Messages within a conversation. Same id scheme as conversations ("m-...").
create table if not exists public.messages (
  id text primary key,
  conversation_id text not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_idx
  on public.messages (conversation_id, created_at);

-- Uploaded / imported document metadata and extracted text. Id scheme matches
-- src/lib/uploads.ts's uid() ("up-...").
create table if not exists public.library_documents (
  id text primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  filename text not null,
  mime_type text,
  byte_size bigint,
  text_content text,
  source text not null default 'upload' check (source in ('upload', 'sharepoint', 'local')),
  external_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists library_documents_user_idx
  on public.library_documents (user_id, updated_at desc);

-- Categorized contacts for the Directory app (UNU, government, NGO, partners).
-- Id scheme matches src/lib/recordId.ts's makeRecordId('dir', ...) ("dir-...").
create table if not exists public.directory_contacts (
  id text primary key,
  category text not null check (category in ('unu', 'government', 'ngo', 'partner', 'other')),
  name text not null,
  role text,
  team text,
  organization text not null,
  email text,
  phone text,
  country text,
  location text,
  expertise text[] not null default '{}',
  tags text[] not null default '{}',
  notes text,
  avatar_initials text,
  avatar_color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists directory_contacts_category_idx
  on public.directory_contacts (category, name);

-- 2026 events matrix (owner: Events app). Ids are short slugs generated by
-- src/lib/recordId.ts (e.g. "ev-s43rsi"), not uuids — keep as text so a
-- record synced from a browser's recordsStore can upsert directly by id.
create table if not exists public.events (
  id text primary key,
  title text not null,
  description text,
  date date,
  date_note text,
  type text not null check (type in (
    'Conference / Symposium', 'Webinar / Seminar',
    'Workshop / Capacity strengthening', 'Policy dialogue / High-level dialogue',
    'Consultation / Roundtable', 'Coordination / Partnership meeting',
    'Side event', 'Other'
  )),
  strategic_purpose text,
  work_package text,
  owner text,
  partners text,
  funder text,
  programme text,
  location text,
  modality text not null default 'Unspecified'
    check (modality in ('In person', 'Virtual', 'Hybrid', 'Unspecified')),
  level text not null default 'Unspecified'
    check (level in ('Global', 'Regional', 'National', 'Sub-national', 'Unspecified')),
  total_participants integer,
  countries_represented text,
  global_south_participants integer,
  global_south_pct numeric,
  female_participants integer,
  female_pct numeric,
  youth_participants integer,
  south_south_exchange boolean,
  key_outputs text,
  internal_file_link text,
  cross_wp_collaboration text,
  website_article text,
  media_coverage text,
  social_media text,
  high_level_participants text,
  updated_at timestamptz not null default now()
);

create index if not exists events_date_idx on public.events (date);

-- 2026 publication mastersheet (owner: Publications app). Same id scheme as
-- events — text slugs like "pub-m5barp" from src/lib/recordId.ts.
create table if not exists public.publications (
  id text primary key,
  title text not null,
  date date,
  first_author text,
  other_authors text,
  type text,
  outlet text,
  link text,
  work_package text,
  target_audience text,
  global_south boolean,
  purpose text,
  updated_at timestamptz not null default now()
);

create index if not exists publications_date_idx on public.publications (date);

-- Row-level security: users only see their own rows.
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.library_documents enable row level security;
alter table public.directory_contacts enable row level security;
alter table public.events enable row level security;
alter table public.publications enable row level security;

-- Pilot policies (open). Tighten once Auth JWT is enforced on every request.
drop policy if exists "profiles read own" on public.profiles;
drop policy if exists "profiles all for service" on public.profiles;
drop policy if exists "conversations all for service" on public.conversations;
drop policy if exists "messages all for service" on public.messages;
drop policy if exists "library all for service" on public.library_documents;
drop policy if exists "directory all for service" on public.directory_contacts;
drop policy if exists "events all for service" on public.events;
drop policy if exists "publications all for service" on public.publications;

create policy "profiles all for service" on public.profiles
  for all using (true) with check (true);

create policy "conversations all for service" on public.conversations
  for all using (true) with check (true);

create policy "messages all for service" on public.messages
  for all using (true) with check (true);

create policy "library all for service" on public.library_documents
  for all using (true) with check (true);

create policy "directory all for service" on public.directory_contacts
  for all using (true) with check (true);

create policy "events all for service" on public.events
  for all using (true) with check (true);

create policy "publications all for service" on public.publications
  for all using (true) with check (true);

-- Note: replace open policies with auth.uid()-scoped RLS before wider launch.
